name: Publish Android

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.16.0'

    - name: Setup rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install x86_64-pc-windows-msvc toolchain
      run: |
        rustup target add x86_64-pc-windows-msvc

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Setup Android NDK
      id: setup-ndk
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r26d
        link-to-sdk: true

    - name: Setup Tauri
      run: |
        npm install
        npx tauri init -A sample-svelte -W sample-svelte -P http://127.0.0.1:5173

    - name: Create .env.loacl
      run: |
        Set-Content -Path .env.loacl -Value "VITE_Mobile_HOST = 0.0.0.0"
        Add-Content -Path .env.loacl -Value "VITE_PORT = 5173"

    - name: Set Config
      run: |
        node ./set-config/set-config.js

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tauri.conf.json
        path: ./src-tauri/tauri.conf.json
        if-no-files-found: error

    - name: Setup Tauri Android
      run: |
        npx tauri android init
      env:
        NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

    - name: Get Keystroe
      run: |
        [System.IO.File]::WriteAllBytes("${{ github.workspace }}/.jks", [Convert]::FromBase64String("${{ secrets.TSCTSC6_KEYSTORE_BASE64 }}"))

    - name: Gen key.properties Files
      run: |
        Set-Content -Path ./src-tauri/gen/android/key.properties -Value "storePassword=${{ secrets.ANDROID_SIGNING_PASSWORD }}"
        Add-Content -Path ./src-tauri/gen/android/key.properties -Value "keyPassword=${{ secrets.ANDROID_SIGNING_PASSWORD }}"
        Add-Content -Path ./src-tauri/gen/android/key.properties -Value "keyAlias=tsctsc6"
        Add-Content -Path ./src-tauri/gen/android/key.properties -Value "storeFile=${{ github.workspace }}/.jks"
    
    - name: Build
      run: |
        npx tauri android build
      env:
        NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        SIGNING_KEY_FILE: ${{ github.workspace }}/.jks
        SIGNING_STORE_PASSWORD: ${{ secrets.ANDROID_SIGNING_PASSWORD }}
        SIGNING_KEY_ALIAS: tsctsc6
        SIGNING_KEY_PASSWORD: ${{ secrets.ANDROID_SIGNING_PASSWORD }}
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bundle
        path: ./src-tauri/gen/android/app/build/outputs/
        if-no-files-found: error
